### PR TITLE
Update subsurf.c

### PR DESCRIPTION
**Pull request by 42TheAnswerToLife**
Bugfixes:
- ensure that all elements in the subtitle note are processed (lines: 973,974,981,1005,1252-1260)

Features:
- implement draw features as proposed by the USF specification (lines: 832-962, 1053-1218)
... 
<shape>                              +-shape      (0..N)*
    <polygon>                          +-polygon   (0..N)*
      <points                           +-points   (2..N)*
       posx="x"                           @-pos x  (1)*
       posy="y" />                        @-pos y  (1)*
    </polygon>
    <rectangle                         +-rectangle (0..N)*
     posx="x"                            @-pos x   (1)*
     posy="y"                            @-pos y   (1)*
     width="width"                       @-width   (1)*
     height="height" />                  @-height  (1)*
    <point                             +-point     (0..N)*
     posx="x"                            @-pos. x  (1)*
     posy="y"                            @-pos. y  (1)*
     diameter="diameter" />              @-diameter(1)*
 </shape>
...

### CODE REVIEW

**Comment by jbkempf** [comment]
Isn't subusf dead?

btw, it's subusf, not subsurf :)

Please check your indentation, remove tabs, and trailing spaces. 
Moreover, are you the one who wrote this code, or was it imported from somewhere else?

**Comment by 42TheAnswerToLife** [comment]
Is subusf dead - good question. The universal subtitle format (USF) was an active open source standard until ~2010. But due to its xml-based representation is very flexibility. 

Currently we are trying to push this standard again to become more common. So we are trying to introduce drawing features like in the ASS  format (cf. libass). So we wrote the code to have a player which is able to visualize the new features, we need to introduce in the USF. 

I'll check my indentation, remove tabs, and trailing spaces.

**Comment by jbkempf** [comment]
OK, that's good. Then, please send it without using github, but on our git.

**Comment by 42TheAnswerToLife** [comment]
Ok thx

**Comment by jbkempf** [comment]
See https://wiki.videolan.org/Git

**Comment by 42TheAnswerToLife** [comment]
;) 
Yes... we normally working with other version management tools. So we will submit our fix and feature plus in the next days. Thank you.

**Comment by jbkempf** [comment]
Did you make it?

**Pull request closed without merging**
