### PR TITLE
sout: h265 rtp packetizer

### PR DESCRIPTION
**Pull request by YouRancestor**

### CODE REVIEW

**Comment by YouRancestor** [comment]
Added a rtp packetizer for h265 coded video stream.

**Comment by jbkempf** [comment]
Please send this to vlc-devel mailing list.

**Comment by jbkempf** [comment]
@YouRancestor where is the packetizer?

**Comment by YouRancestor** [comment]
Here is my packetizer. @jbkempf 
https://github.com/YouRancestor/vlc/commit/e0a2798b82746e6230973f4cec07915eebf6af3c
https://github.com/YouRancestor/vlc/tree/sout_rtp_hevc_pack
Sorry, I make the request with a wrong branch. I even didn't notice that until you ask me this question.
And I found that there has been an another implementation in recent videolan/vlc/master, and may be better than mine.
So you could have closed this pull request.

**Comment by liyoubdu** [comment]
@YouRancestor, which file is the packetizer in in recent vlc/master?

**Comment by YouRancestor** [comment]
[vlc/modules/stream_out/rtpfmt.c](https://github.com/videolan/vlc/blob/master/modules/stream_out/rtpfmt.c)
@liyoubdu

**Pull request merged**
