### PR TITLE
Correcting Swedish desktop description

### PR DESCRIPTION
**Pull request by hanklank**
Correcting Swedish translation of desktop name to be in style of other FOSS-translations, that is [program name description noun] instead of the other way round (as was).

### CODE REVIEW

**Comment by hanklank** [comment]
@jbkempf Anything wrong with this small translation correction as it was closed and not merged?

**Comment by haaninjo** [comment]
The changes look fine to me. They are consistent with what we use in the GNOME translation group. Having the name VLC first in the long name string is a good idea since that ensures that the program is sorted under V in menus.

At present VLC is sorted under "M" in the Swedish menus of for example Xfce which makes it harder to find the program.

**Comment by jbkempf** [comment]
This was fixed, and pushed.

**Comment by GitSoftwareNow** [comment]
when I build vlc source code vlc 2.8.0 the gcc compiler reports an error,it discribes that video_chroma/i420_rgb16_x86.c: 在函数‘I420_R5G6B5’中:
video_chroma/i420_rgb16_x86.c:335: 编译器内部错误：在 memory_address 中，于 explow.c:493

**Pull request closed without merging**
