### PR TITLE
Added avs2 and avs3 decoders.

### PR DESCRIPTION
**Pull request by xatabhk**
Added avs2 and avs3 decoders for VLC.

### CODE REVIEW

**Comment by chouquette** [comment]
Hi,

This looks like a very decent MR, but this is a mirror and nothing gets reviewed here. Please refer to https://wiki.videolan.org/Sending_Patches_VLC/

**Comment by jbkempf** [comment]
Please split this merge request in 4 or 5 commits, btw.

I don't see why you modify ffmpeg and the GPL part of it.

**Comment by xatabhk** [comment]
> Please split this merge request in 4 or 5 commits, btw.
> I don't see why you modify ffmpeg and the GPL part of it.
Because the avs3 decoding is done by a modified ffmpeg. Maybe it is better to create a vlc pull request for avs2 and a ffmpeg one for avs3 first.

**Comment by jbkempf** [comment]
> > Please split this merge request in 4 or 5 commits, btw.
> > I don't see why you modify ffmpeg and the GPL part of it.

>  Because the avs3 decoding is done by a modified ffmpeg. Maybe it is better to create a vlc pull request for avs2 and a ffmpeg one for avs3 first.

Yes

**Pull request closed without merging**
