### PR TITLE
*We are seeing the crash while closing the VLC app.

### PR DESCRIPTION
**Pull request by Niranjan2110**
*For the CleanupReason = CLEANUP_INTF_CLOSED, p_initf_p_mi structure was not destroyed, and the pointer is not being NULL. *This Resulted into Following Assertion - assert(p_var->list_callbacks == NULL).
* Fix is - deleted the structure and pointer being NULL for p_intf->p_mi.

### CODE REVIEW

**Comment by Niranjan2110** [comment]
Steps to Repro the VLC crash issue:

1. Start the VLC app
2. play some video
3. close the VLC app

VLC will crash with error "assert(p_var->list_callbacks == NULL)"

**Comment by fkuehne** [comment]
Please see https://code.videolan.org/videolan/vlc for contributions.

**Comment by Carter-chao** [comment]
> Please see https://code.videolan.org/videolan/vlc for contributions.
I found a serious memory leak problem with playing videos using vaapi, which was encountered by various platforms,
I want to submit pr, but I cannot register the gitlab account of vlc

image

**Comment by Carter-chao** [comment]
> Please see https://code.videolan.org/videolan/vlc for contributions.
image

I found a serious memory leak problem with playing videos using vaapi, which was encountered by various platforms,
I want to submit pr, but I cannot register the gitlab account of vlc

**Comment by Niranjan2110** [comment]
Thanks for the info. wanted to know when will Windows on Arm VLC 4.x will available . We are looking for release date for VLC 4.x windows on Arm

**Pull request closed without merging**
