### PR TITLE
Create vrt.lua

### PR DESCRIPTION
**Pull request by midas02**
Open VRT videos in VLC (www.vrt.be)

This is the very first time I'm adding something on Github, and I have no scripting experience whatsoever. Please advise if this can be added and/or if modifications are needed.

### CODE REVIEW

**Comment by ePirat** [comment]
Please send this to the VLC developer mailing list instead, as VLC does not use Github PRs.

**Comment by midas02** [comment]
Hello @ePirat, thanks for the advise. I had been looking at https://github.com/videolan/vlc/tree/master/share/lua in search of inspiration to create this script, but there was no mentioning of where to upload the files. So it's probably best if someone would mention it in the readme file.

On uploading the changes. I just spent more than half an hour trying to follow everything that has been laid out here (https://wiki.videolan.org/Sending_Patches_VLC/), and I have given up. It seems I would need to download/install a complete stand-alone coding environment, figure out how to use it, 'make your changes' (it's not even mentioned how), etcetera, etcetera, etcetera. And all of this for a simple script, which doesn't interfere with the rest of the environment. That's too much to ask. If you, or anyone else who is used to this environment, wants to take the file through the motions, feel free. You'll be doing the people who could use this extension a favour. But I'm not going to spend hours and hours trying to figure it out.

- And again, I'm not a coder. The code is rather rough, but it gets the work done. If anyone feels there are more elegant ways to serve the purpose, feel free to adapt. - 

Best regards
Gautier

**Comment by holocronweaver** [comment]
*facepalm* C'mon VLC devs...your submission policies look like something from 2002.

**Comment by geecko86** [comment]
Hey there fellow Belgian,

Yes, they're very old school. But on top of that I don't think this Pull Request fits the scope of this project. I don't think VLC aims to "take" ad revenue away from content providers.

**Comment by FERMAT1991** [comment]
I have an issue and I didn't find where to put it so I post it here the issue is the recording button can't record the first seconds of the video.

**Comment by ePirat** [comment]
This is not the place to report bugs or seek help. Bugs should be reported at [trac.videolan.org](https://trac.videolan.org/vlc/) and for help, create a post in [forum.videolan.org](https://forum.videolan.org) please.

**Comment by DerpChest** [comment]
I did not know VLC uses some lua.

**Pull request closed without merging**
